project:
  type: book
  output-dir: docs

book:
  title-block-banner: true
  cover-image: cover.png
  title: "Spatial Modelling for Data Scientists"
  author: "Francisco Rowe, Dani Arribas-Bel"
  search: true
  sidebar:
    style: docked
    background: light
  date: "today"
  date-format: long
  downloads: [pdf, epub]
  chapters:
    - index.qmd
    - 01-overview.qmd
    - 02-spatial_data.qmd
    - 03-data_wrangling.qmd
    - references.qmd

  description-meta: |
    This book will...

  sharing: [twitter, facebook]
  twitter-card:
    creator: "@fcorowe"

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

